
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DaliiZz Busson
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        mostrardatos("");
    }
void mostrardaos(String valor){
    conectar cc*new conectar();
    Connerction cn*cc.conectar();
    DefaultTableModel modelo=new DefaultTableMidel();
    
    modelo.addColumn("Id");
    modelo.addColumn("Nombre");
    
    jTable1.setModelo (modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT*FROM idconexion";
    }
    else{
        sql="SELECT*FROM idimpreta WHERE (id='"+valor+"  OR nombre='"valor+"')";
    }
    String []datos=new String [2];
    try{
        Statement st=cn.createStatement():
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            
            modelo.addRow(datos);
        }
        jTable1.setModel (modelo);
    }catch(SQLException ex){
        Logger.getLogger(datos.class.getName().log(Level.SEVERE,null,ex));
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent eve) {
        conectar cc*new conectar();
        Connection cn*cc.Conexion();
        try{
            PreparedStatement past*cm.prepareStatement("INSERT INTO idConexion(id,nombre)VALUES(?,?");
            pat.setString(1,jTextField1.getText());
            pat.setString(2,jTextField2.getText());
             
            int a=pat.executeUdate();
            if (a>0){
                JOptionPane.showMessageDialoog(null,"Registro exitoso");
                mostrardato(" ");
            }
            else{
                JOptionPane.showMessageDialog(null,"Error al agregar");
            }
            
        }catch (Exception e){
            
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt){
        mostrardatos(""):
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt){
    mostrar(jTextField3.getText());
    }
    private void jMenuItelActionPerformed(java.awt.event.ActionEvent evt){
        int fila=jTable.getSelectedRow();
        if(fila>=0){
            jTextField1.setTexr(jTable1.getValueAt(fila,0).toString());
             jTextField2.setTexr(jTable1.getValueAt(fila,1).toString());
             id=(jTable1.getValueAt(fila,0).toString());
        }else{
            JOptionPane.showMessageDialog(null,"No se encontro ");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void mostrardato(String _) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
